### ISSUE TITLE
check ok/cancel for macro

### ISSUE THREAD

**Issue by alkabal** [wolfmanjm/kivy-smoothie-host#10]
Hi

I think maybee wrong thinking... something like this can be usefull before execute some macro.

https://github.com/wolfmanjm/kivy-smoothie-host/blob/0d93270cc518f88891398212144ce0638ca5b301/main.py#L673

I don't found myself  the good way for make this possible : sorry !

Br

**Comment by wolfmanjm** [comment]
already have macros that can prompt for input

**Comment by alkabal** [comment]
yes you are right but the actual prompt ask for put some value.

In some case we can like to have only ok / cancel without input box.
