### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by alfie0** [wolfmanjm/kivy-smoothie-host#12]
Great job!

**Comment by wolfmanjm** [comment]
no, it won't work on android

**Comment by alfie0** [comment]
VScode prompts that comms-net.py and comms.py have a syntax error, respectively, and how to modify it?

[cid:image001.jpg@01D5401E.C6419140]

[cid:image002.jpg@01D5401E.DDAEBAB0]
发件人: Jim Morris<mailto:notifications@github.com>
发送时间: 2019年7月21日 16:29
收件人: wolfmanjm/kivy-smoothie-host<mailto:kivy-smoothie-host@noreply.github.com>
抄送: alfie0<mailto:chen.alfie@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [wolfmanjm/kivy-smoothie-host] Android (#12)


no, it won't work on android

**Comment by wolfmanjm** [comment]
I have no idea what VSCode is. you do not say what the error is so I can't help you.

Do check you are using an appropriate version of python and the support libraries as documented in the readme.

**Comment by alfie0** [comment]
VScode is VisualStudioCode, uses python 3.7. I try create a apk package for android using the kivy Buildozer tool, “Comms” and “comms-net” is prompted for invalid syntax during Buildozer compilation. The picture is the error process.

[cid:image003.png@01D54025.CE5D3440]

**Comment by wolfmanjm** [comment]
Python 3.7 is very clearly stated in the README as NOT being supported you cannot use it period.
As I said this WILL NOT run on android either.

Please read the readme thoroughly before reporting issues, thank you.

**Comment by alfie0** [comment]
I see. Thank you for your reply.

Best Regards.
