### ISSUE TITLE
For CNC

### ISSUE THREAD

**Issue by alkabal** [wolfmanjm/kivy-smoothie-host#18]
It is possible to remove Power and Laser from DRO in CNC mode and replace by Spindle speed and spindle override ?

Br

**Comment by wolfmanjm** [comment]
no

**Comment by wolfmanjm** [comment]
The reason is lasers are also set to CNC and that is useful information I want to see. Also there is no such thing as spindle speed in Smoothie for most people as spindle is an optional module unused by most people.

**Comment by alkabal** [comment]
Ok i understand no pb, this is only a useless things.

Br
