### ISSUE TITLE
Print from USB memory stick

### ISSUE THREAD

**Issue by pedroset** [wolfmanjm/kivy-smoothie-host#19]
Hello! Thank you for the awesome work!!

I'd like to know if it is possible to open files from a usb stick, or the only way to print a file is from the RPI microSD. I mean, every time i have a new file to print i have to take the sd off the pi, save the file using my desktop PC and then put the SD back in?

I tried all i could, but i didn't find a way... i'm not good with linux either hehehe

**Comment by wolfmanjm** [comment]
Yes there is a way, but it is not really a smoopi issue it is an rpi/linux issue... google for mounting usb sticks on rpi. There was a guide I saw somewhere if I find it I'll post it here.

**Comment by wolfmanjm** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?t=205016#p1271455

**Comment by pedroset** [comment]
thank you very much, i will try that! Another silly question, how do i quit smoopi back to the command shell without reloading smoopi automatically?

**Comment by wolfmanjm** [comment]
if you are using the runit then the only way to stop smoopi is to ssh in and do `sudo sv down /etc/service/smoopi`

**Comment by pedroset** [comment]
allright!! thank you again

**Comment by pedroset** [comment]
Great!

 You just have to iunstall usb mount `sudo apt-get install usbmount` then change MountFlags=slave to MountFlags=shared here:

sudo nano /lib/systemd/system/systemd-udevd.service

as they describe in the link you sent. After rebooting any usb drive will be mounted to /media/usb0

**Comment by wolfmanjm** [comment]
then to access it from smoopi you may have to do a symbolic link to /media/usb0 from the home directory.

**Comment by pedroset** [comment]
first test with smoopi, running great!

https://www.youtube.com/watch?v=k0XY-VG3Zy4
