### ISSUE TITLE
Is it possible to have 4 extruders and show the temperature for all and the bed on one screen

### ISSUE THREAD

**Issue by DouglasPearless** [wolfmanjm/kivy-smoothie-host#2]
In the following screen, is it possible to have T0/1/2/3 and Bed all displaying rather than having to toggle T0/1 etc?

<img width="1411" alt="Smoopi" src="https://user-images.githubusercontent.com/3744251/56259897-e62ff700-6128-11e9-9595-4bc520adf406.png">

**Comment by wolfmanjm** [comment]
It is probably possible if you make your own large desktop layout. It certainly is not possible on an RPI touch screen.
