### ISSUE TITLE
Allow automount usb with debian image

### ISSUE THREAD

**Issue by alkabal** [wolfmanjm/kivy-smoothie-host#21]
Hi

Following this guide i have succefully instaled and used usbmount
https://doc.ubuntu-fr.org/usbmount

For make user life more easy i have also edited the files  /etc/usbmount/usbmount.conf
MOUNTPOINTS="/home/pi/gcode/usb0 /home/pi/gcode/usb1"

I suggest you to add this to the default image

I appologize if this is not wanted but the only method i know for send file to smoopi is ssh with winscp and this is easy for me but not for familly usage.

Br

**Comment by wolfmanjm** [comment]
Thanks.

**Comment by alkabal** [comment]
I don't know if you like it but if you do the change, another suggestion is add a unmout button on your interface.

Br
