### ISSUE TITLE
Image doesnt work

### ISSUE THREAD

**Issue by lilarc** [wolfmanjm/kivy-smoothie-host#25]
Ive been runing Smoopi for 2 years on a little cnc and it worked great till sd get corrupted.
New image seems to be incomplete, its only  564 mb zip.
The old image i have stored its from 2019 and it cant reach to update, this one still say print instead of run.
Thanks a lot for your great job and efforts.

**Comment by wolfmanjm** [comment]
sounds like you got a corrupt download, where did you download it from?

**Comment by wolfmanjm** [comment]
It seems the zip file is not on smoothieware.org anymore, I'll upload a new one later tonight.

**Comment by wolfmanjm** [comment]
I have uploaded the image again it is 1576496042bytes. Please try again.

**Comment by wolfmanjm** [comment]
Seems you may have to copy and paste the URL into your browser as clicking on it doesn't seem to work.
http://smoothieware.org/_media/bin/smoopi_img2.zip

**Comment by lilarc** [comment]
Now it works great
thx  a lot
