### ISSUE TITLE
feature request: shell like prompt history and navigation

### ISSUE THREAD

**Issue by evils** [wolfmanjm/kivy-smoothie-host#28]
i find myself repeating things like `M119` (to check the state of the limit switches while setting them up)

i'd be quite nice if i could just `arrow up` to repeat previous commands, just like a regular shell
navigating within a command with things like `ctrl - a` and `ctrl - e` to jump to the start and the end, would also be great
these are things implemented by [GNU readline](https://en.wikipedia.org/wiki/GNU_Readline#Bindings), which is supposed to be exposed in python as `readline`
but i'm not familiar with python, so couldn't say if that makes it convenient to use here

**Comment by wolfmanjm** [comment]
on a desktop installation Ctrl-P will repeat the last command, on a touch screen there is a repeat button.
