### ISSUE TITLE
Feature Request - More prominent 10x tick-box in the Jog interface

### ISSUE THREAD

**Issue by jtotham** [wolfmanjm/kivy-smoothie-host#5]
Please can the 10x tick-box in the Jog interface be made into a more prominent button? 

It's super handy but the tiny tickbox is kind of awkward to toggle on and off in RPI layout.

**Comment by wolfmanjm** [comment]
It is actually quite usable I use it all the time and I have fat fingers! you need to hit the check box not the title.
I'll consider changing it to a toggle button, but then the issue is always if the label should be what it currently is or what it will be if you hit the button.
