### ISSUE TITLE
Feature Request - Spindle Control from the MPG Panel

### ISSUE THREAD

**Issue by jtotham** [wolfmanjm/kivy-smoothie-host#6]
Please could you look at adding spindle control to the the MPG panel, being able to bump the spindle speed mid run would be super handy.

**Comment by wolfmanjm** [comment]
I'm not likely to add this as I do not use the spindle module which is the only thing that supports the spindle speed.
You could use a macro button to increase the spindle speed to a set value, or just issue a console code.
