### ISSUE TITLE
checking is_suspend allways false

### ISSUE THREAD

**Issue by alkabal** [wolfmanjm/kivy-smoothie-host#9]
https://github.com/wolfmanjm/kivy-smoothie-host/blob/9fdf303f7ba0e17378db9bc48e6db6f056aa1705/modules/hb04.py#L341

Hi

I'm really unsure but for what i have see i think this check does not work correctly, you need to use "self.app.main_window.start_print()"

Br

**Comment by wolfmanjm** [comment]
it is correct as is
